# Generated by Django 3.2.10 on 2024-03-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Mail', models.CharField(default='', max_length=50)),
                ('Number', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=50)),
                ('PinCode', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
