# Generated by Django 3.2.10 on 2024-03-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Train',
            new_name='Booking',
        ),
    ]
